config/routes.rb
CbuHome::Application.routes.draw do
  root :to => "admin#login"

match 'admin/logout' => 'admin#logout'
match 'pages/home' => 'pages#home'
match 'pages/resources' => 'pages#resources'
match 'pages/about' => 'pages#about'
match 'pages/contact' => 'pages#contact'
match 'admin/index' => 'admin#index'

match 'orders/index' => 'orders#index'
match 'cbustore' => 'cbustore#index'
match 'cbustore/add_to_request' => 'cbustore#add_to_request'
match 'cbustore/empty_cart' => 'cbustore#empty_cart'
match 'cbustore/checkout' => 'cbustore#checkout'
match 'cbustore/save_order' => 'cbustore#save_order'
match 'cbus/map' => 'cbus#map'

resources :users
resources :line_items
match 'cbus/map' => 'cbus#map'
match 'offices/map' => 'offices#map'
match 'orders/map' => 'orders#map'
resources :orders
resources :offices
resources :cbus
resources :migrations

end

app/models/office.rb
class Office < ActiveRecord::Base
  self.include_root_in_json = false
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.xml
  def index
    @offices = Office.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.xml
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @office }
      format.json { render :json=> @office }
    end
  end
  
  def map
#    @cbus = Cbu.all(:limit=>20, :offset=>70)
    @offices = Office.all
    respond_to do |format|
      format.html
    end
  end
  
  # GET /offices/new
  # GET /offices/new.xml
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.xml
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        flash[:notice] = 'Office was successfully created.'
        format.html { redirect_to(@office) }
        format.xml  { render :xml => @office, :status => :created, :location => @office }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.xml
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        flash[:notice] = 'Office was successfully updated.'
        format.html { redirect_to(@office) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @office.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.xml
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to(offices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<% form_for(@office) do |f| %>
  <%= f.error_messages %>
<p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  
  
    <%= f.label :postoffice %>
    <%= f.text_field :postoffice %>
  
  
    <%= f.label :state %>
    <%= f.text_field :state %>
  
  
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </p>
  <p>
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </p>
  <p>
    <%= f.label :lng %>
    <%= f.text_field :lng %>
  </p>
   
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>Listing offices</h1>

<table>
  <tr>
    <th>address</th>
    <th>city</th>
    <th>state</th>
    <th>zip</th>
    <th>lat</th>
    <th>lng</th>
    
  </tr>
  
<% @offices.each do |office| %>

  <tr>
  	<td><%=h office.address %></td>
    <td><%=h office.city %></td>
    <td><%=h office.state %></td>
    <td><%=h office.zip %></td>
    <td><%=h office.lat %></td>
    <td><%=h office.lng %></td>
    
  
  
    <td><%= link_to 'Show', office %></td>
    <td><%= link_to 'Edit', edit_office_path(office) %></td>
    <td><%= link_to 'Destroy', office, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New office', new_office_path %>

app/views/offices/map.html.erb
  <script src="http://maps.google.com/maps?file=api&v=2&key=ABQIAAAAjikXrE5Nw2qkAh2pV1AndBRd_f1wgoxrA90ATXKnKNuxhfd85BR749SJbLz1tXsn07_Es6HzO_rodg" type="text/javascript"></script>
  <%=javascript_include_tag 'maps_offices.js' %>
   <script>var offices= <%=@offices.to_json%>;  </script>


  <h1>  OFFICE LOCATION MAP  </h1>
  <div id="map" style="width: 900px; height: 700px"></div>
 Some other content here

app/views/offices/new.html.erb
<h1>New office</h1>

<% form_for(@office) do |f| %>
  <%= f.error_messages %>
<p>
    <%= f.label :address %>
    <%= f.text_field :address %>
  
  
    <%= f.label :postoffice %>
    <%= f.text_field :postoffice %>
  
  
    <%= f.label :state %>
    <%= f.text_field :state %>
  
  
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </p>
  <p>
    <%= f.label :lat %>
    <%= f.text_field :lat %>
  </p>
  <p>
    <%= f.label :lng %>
    <%= f.text_field :lng %>
  </p>
   
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
p>
  <b>address:</b>
  <%=h @office.address %>
</p>
<p>
  <b>Post Office:</b>
  <%=h @office.city %>
</p>
<p>
  <b>State:</b>
  <%=h @office.state %>
</p>
<p>
  <b>zip:</b>
  <%=h @office.zip %>
</p>
<p>
  <b>lat:</b>
  <%=h @office.lat %>
</p>
<p>
  <b>lng:</b>
  <%=h @office.lng %>
</p>


<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>