config/routes.rb
CbuHome::Application.routes.draw do
  root :to => "admin#login"

match 'admin/logout' => 'admin#logout'
match 'pages/home' => 'pages#home'
match 'pages/resources' => 'pages#resources'
match 'pages/about' => 'pages#about'
match 'pages/contact' => 'pages#contact'
match 'admin/index' => 'admin#index'

match 'orders/index' => 'orders#index'
match 'cbustore' => 'cbustore#index'
match 'cbustore/add_to_request' => 'cbustore#add_to_request'
match 'cbustore/empty_cart' => 'cbustore#empty_cart'
match 'cbustore/checkout' => 'cbustore#checkout'
match 'cbustore/save_order' => 'cbustore#save_order'
match 'cbus/map' => 'cbus#map'

resources :users
resources :line_items
match 'cbus/map' => 'cbus#map'
match 'offices/map' => 'offices#map'
match 'orders/map' => 'orders#map'
resources :orders
resources :offices
resources :cbus
resources :migrations

end

app/controllers/cbustore_controller.rb
class CbustoreController < ApplicationController
  def index
    @cbus = Cbu.find_cbu_for_work
    #this next line is added from page 121 for the ajax code
    @cart = find_cart
  end

# the following is from page 102 and page 113
  def add_to_request
    cbu = Cbu.find(params[:id])
    @cart = find_cart
    @cart.add_cbu(cbu)
    redirect_to_index

# the following is from page 109
  rescue ActiveRecord::RecordNotFound
    logger.error("Attempt to access invalid cbu #{params[:id]}")
#    flash[:notice] = "Invalid CBU address"
#    redirect_to :action => 'index'
    redirect_to_index("Invalid CBU address")
  end

# the following is from page 112 and page 113
  def empty_cart
    session[:cart] = nil
#    flash[:notice] = "Your Request List is currently empty"
#    redirect_to :action => 'index'
    redirect_to_index("Your Request List is currently empty")
  end

# the following is from page 145
def save_order
    @cart = find_cart
    @order = Order.new(params[:order])
    @order.add_line_items_from_cart(@cart)
    if @order.save
      session[:cart] = nil
      redirect_to_index("Request submitted - add more or finish")
    else
      render :action => 'checkout'
    end
  end


  # Headfirst page 174
  def find
     @order = Order.find_all_by_route_number(params[:search_string])
  end


 def checkout
  @cart = find_cart
  if @cart.items.empty?
    redirect_to_index("Your cart is empty")
  else
    @order = Order.new
  end
end




# the following is from page 167
protected
def authorize
end


#the following is from page 101
private

def redirect_to_index(msg = nil)
  flash[:notice] = msg if msg
  redirect_to :action => 'index'
end
# the following is from page 101
  def find_cart
   session[:cart] ||= Cart.new    #later on page 172 the book makes this
                                  #@cart = (session[:cart] ||= Cart.new)
                                  # additionally adds to the cbustore_controller.rb
                                  # before_filter :find_cart, :except => :empty_cart
                                  #final listing is shown on page 696
  end
end

app/helpers/cbustore_helper.rb
module CbustoreHelper
  
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

  

app/views/cbustore/_cart.html.erb
<div class="cart-title"> CBU address for Work Request</div>
<table>
			<%= render(:partial => "cart_item", :collection => cart.items) %>



</table>
<%= button_to 'Change this Address', cbustore_empty_cart_path %>
<%= button_to "Add Problem Details" , cbustore_checkout_path %>

app/views/cbustore/_cart_item.html.erb
<tr>
			<th>Route Number</th>
			<th>Address</th>
</tr>

<tr>
		<td><%= cart_item.route_number%></td>
		<td><%= cart_item.address %></td>
</tr>	

app/views/cbustore/_user_orderlist.html.erb
<h1>Open request orders</h1>
<table>
  <tr>
  	<th>Route</th>
    <th>Address</th>
    <th>Locker Number</th>
    <th>Problem</th>
    <th>Description</th>
    <th>Date</th>
  </tr>
<%for order in orders %>
  <tr>
    <td><%=h order.line_items[0].cbu.route_number if order.line_items[0] %></td>
    <td><%=h order.line_items[0].cbu.address if order.line_items[0] %></td>
    <td><%=h order.locker %></td>
    <td><%=h order.problem %></td>
    <td><%=h order.description %></td>
    <td><%=h order.date %></td>
  </tr>
<%end%>
</table>
<%= link_to 'Map these CBUs' , orders_map_path %><br />

app/views/cbustore/checkout.html.erb
<div class="request-form">
  <%= error_messages_for 'order' %>
  <%= form_for @order do |form| %>
	<fieldset>
      <legend>Please Enter Your Details</legend>
<div>
<%= form.label :locker,"Locker:" %>
<%= form.select :locker,Order::LOCKER_NUM,:prompt => "Select a locker number" %>
</div><br/>
<div>
<%= form.label :problem, "Problem:" %>
<%= form.select :problem,Order::PROBLEM_TYPES,:prompt => "Select a problem" %>
</div><br/>
<div>
<%= form.label :description, "Description:" %>
<%= form.text_area :description, :rows => 5, :cols => 40 %>
</div><br/>
<div>
<%= form.label :date, "Date:" %>
<%= form.text_field :created_at, :size => 10 %>
</div>

<%= submit_tag "Place Order", :class => "submit" %>
	</fieldset>
	<%end%>
</div>

app/views/cbustore/find_search.html.erb
<h1>Listing Your CBU for Address - <%= params[:search_string]%></h1>

<table>
		<tr>
			<th>Route Number</th>
			<th>Address</th>
		</tr>

	<% for cbu in @cbus %>	
		<tr>
			<td><%=h cbu.route_number%></td>
			<td><%=h cbu.address%></td>
			<td><%= button_to 'Add to Request', :action => 'add_to_request', :id => cbu %></td>
		</tr>
	<% end %>
</table>

app/views/cbustore/index.html.erb
<h1>Your CBU Address Catalog</h1>
( click the "add to request" button for problem location )


<table>
		<tr>
			<th>Route Number</th>
			<th>Address</th>
		</tr>

	<% for cbu in @cbus %>
		<tr>
			<td><%=h cbu.route_number%></td>
			<td><%=h cbu.address%></td>
			<td><%= button_to 'Add to Request', cbustore_add_to_request_path(:id => cbu)%>
      </td>
		</tr>
	<% end %>
</table>