config/routes.rb
CbuHome::Application.routes.draw do
  root :to => "admin#login"

match 'admin/logout' => 'admin#logout'
match 'pages/home' => 'pages#home'
match 'pages/resources' => 'pages#resources'
match 'pages/about' => 'pages#about'
match 'pages/contact' => 'pages#contact'
match 'admin/index' => 'admin#index'

match 'orders/index' => 'orders#index'
match 'cbustore' => 'cbustore#index'
match 'cbustore/add_to_request' => 'cbustore#add_to_request'
match 'cbustore/empty_cart' => 'cbustore#empty_cart'
match 'cbustore/checkout' => 'cbustore#checkout'
match 'cbustore/save_order' => 'cbustore#save_order'
match 'cbus/map' => 'cbus#map'

resources :users
resources :line_items
match 'cbus/map' => 'cbus#map'
match 'offices/map' => 'offices#map'
match 'orders/map' => 'orders#map'
resources :orders
resources :offices
resources :cbus
resources :migrations

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title><%= @pagetitle%></title>
  <%= stylesheet_link_tag 'pages' %>

</head>
<body>
		<div id='pagewrapper'>
			<div id='header'>
				<p>Maintenance CBU Repair Request Application</p>
		  </div>
			<div id='navbar'>
				<ul>
					<li><%= link_to 'Home', {:controller => 'pages', :action => 'home'} %></li>
					<li><%= link_to 'Resources', {:controller => 'pages', :action => 'resources'} %></li>
			    <li><%= link_to 'About Us', {:controller => 'pages', :action => 'about'} %></li>
			    <li><%= link_to 'Contact Us', {:controller => 'pages', :action => 'contact'} %></li>
				</ul>

</div>
		<div id='content'>
	<%= yield %>
</div>
		<div id='footer'>
			<p>Learning Rails Sample Application</p>
		</div>
</body>
</html>

app/views/layouts/application_new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CbuHome</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title><%= @pagetitle%></title>
  <%= stylesheet_link_tag 'pages' %>
  
</head>
<body>
		<div id='pagewrapper'>
			<div id='header'>
				<p>Maintenance CBU Repair Request Application</p>
		  </div>
			<div id='navbar'>
				<ul>
					<li><%= link_to 'Home', {:controller => 'pages', :action => 'home'} %></li>
					<li><%= link_to 'Resources', {:controller => 'pages', :action => 'resources'} %></li>
			    <li><%= link_to 'About Us', {:controller => 'pages', :action => 'about'} %></li>
			    <li><%= link_to 'Contact Us', {:controller => 'pages', :action => 'contact'} %></li>
				</ul>

</div>
		<div id='content'>
	<%= yield %>
</div>
		<div id='footer'>
			<p>Learning Rails Sample Application</p>
		</div>
</body>
</html>

app/views/layouts/cbustore.html.erb
<html>
    <head>
        <title>CBU Parcel Locker Repairs</title>
        <%= stylesheet_link_tag "cbuwork", :media => "all" %>
    </head>
    <body id="cbustore">
        <div id="banner">
            <%= image_tag("cluster_box_unit.png") %>
            <%= @page_title || "CBU Parcel Locker Repair Request" %>

            <span style="text-align:right">
            <%= form_tag "/cbus/find" do %>
                <%= text_field_tag :search_string %>
                <%= submit_tag "search" %>
                <%end %>
            </span>


<div id='navbar'>
<ul>
<li><%= link_to 'Home', {:controller => 'pages', :action => 'home'} %></li>
<li><%= link_to 'Resources', {:controller => 'pages', :action => 'resources'} %></li>
<li><%= link_to 'About Us', {:controller => 'pages', :action => 'about'} %></li>
<li><%= link_to 'Contact Us', {:controller => 'pages', :action => 'contact'} %></li>
</ul>

</div>

<!--        <div id="columns">!-->
    <div id="side">
    	<% if @cart %>
		    <% hidden_div_if(@cart.items.empty?, :id => "cart") do %>
		    <%= render(:partial => "cart", :object => @cart) %><br/>
<!--		<%= render(:partial => "user_orderlist", :locals =>{:orders=>Order.find(:all)}) %>    !-->
		<%end%>
	<%end%>
<% if session[:user_id] %>
   <br />

   <%= link_to 'Orders' ,   :controller => 'orders' %><br />
   <%= link_to 'Request Repairs' , cbustore_path %><br />

   <%= link_to 'CBU Inventory' , :controller => 'cbus' %><br />
   <%#= link_to 'Map CBUs' , :controller => 'cbus/map' %><br />
   <%= link_to 'Map CBUs', cbus_map_path %><br />
   <%#= link_to 'Archived Orders' ,   :controller => 'orders',:archive=>"true"%><br />
   <%= link_to 'Archived Orders' , orders_path(:archive => true)%><br />
   <%#= link_to 'Archived Orders' ,   :controller => 'orders',:archive=>"true"%><br />
   <br />

   <%= link_to 'Users' ,    :controller => 'users' %><br />
   <br />
   <%= link_to 'Logout', admin_logout_path %>
<%end%>
</div>
<div id="main">
	<% if flash[:notice] -%>
	   <div id="notice"><%= flash[:notice] %></div>
	<% end -%>
<%= yield :layout %>
  </div>
</div>
</body>
</html>

app/views/layouts/line_items.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>LineItems: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>

app/views/layouts/offices.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Offices: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>